version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./backend/mongodb/dump:/docker-entrypoint-initdb.d/mongodb
      - ./backend/mongodb/scripts/import_cmd.sh:/docker-entrypoint-initdb.d/import_cmd.sh
    command:
      /docker-entrypoint-initdb.d/import_cmd.sh

  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
