version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    networks:
      - deviceRouter
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo_seed:
    image: mongo
    networks:
      - deviceRouter
    links:
      - mongo
    volumes:
      - ./backend/mongodb/dump:/docker-entrypoint-initdb.d/mongodb
      - ./backend/mongodb/scripts/import_cmd.sh:/docker-entrypoint-initdb.d/import_cmd.sh
    command:
      /docker-entrypoint-initdb.d/import_cmd.sh

  backend:
    build: ./backend
    hostname: backend
    networks:
      - deviceRouter
    ports:
      - 5000:5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    hostname: frontend
    networks:
      - deviceRouter
    ports:
      - 80:80
    depends_on:
      - backend

  device:
    build: ./test_device
    tty: true
    ports:
      - "1022:22"
    restart: unless-stopped
    networks:
      - deviceRouter

networks:
  deviceRouter:
    driver: bridge
    name: device_router
