version: "3.8"

services:
  device:
    build: .
    tty: true
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command:
      - /docker-entrypoint-initdb.d/config_test_device.sh
    ports:
      - "22:22"
    restart: unless-stopped

networks:
  default:
    external:
      name: device_router
